from datetime import date
from typing import Protocol
from uuid import UUID

from core.domain.models import Account, Asset, Snapshot


class AccountRepository(Protocol):
    def get_all(self, include_inactive: bool = False) -> list[Account]: ...
    def get_by_id(self, id: UUID) -> Account | None: ...
    def save(self, account: Account) -> Account: ...
    def update(self, account: Account) -> Account: ...


class SnapshotRepository(Protocol):
    def get_for_account(self, account_id: UUID) -> list[Snapshot]: ...
    def get_latest_for_all(self) -> dict[UUID, Snapshot]: ...
    def get_latest_as_of(self, as_of: date) -> list[Snapshot]: ...
    def get_earliest_date(self) -> date | None: ...
    def save(self, snapshot: Snapshot) -> Snapshot: ...
    def update(self, snapshot: Snapshot) -> Snapshot: ...
    def delete(self, account_id: UUID, snapshot_id: UUID) -> None: ...


class AssetRepository(Protocol):
    def get_all(self, include_inactive: bool = False) -> list[Asset]: ...
    def get_by_id(self, id: UUID) -> Asset | None: ...
    def save(self, asset: Asset) -> Asset: ...
    def update(self, asset: Asset) -> Asset: ...
